services:
  registry:
    image: registry:2
    container_name: server-docker-registry
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - registry_data:/data
      - ./registry-config.yml:/etc/docker/registry/config.yml:ro
    restart: unless-stopped

volumes:
  registry_data: