services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-jobspy}
      - POSTGRES_USER=${POSTGRES_USER:-jobspy}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-jobspy_password}
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-jobspy} -d ${POSTGRES_DB:-jobspy}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: 
      context: https://github.com/gilby125/jobspy-api.git#main
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8787:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-jobspy}:${POSTGRES_PASSWORD:-jobspy_password}@postgres:5432/${POSTGRES_DB:-jobspy}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_API_KEY_AUTH=${ENABLE_API_KEY_AUTH:-false}
      - API_KEYS=${API_KEYS:-}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-false}
      - DEFAULT_SITE_NAMES=${DEFAULT_SITE_NAMES:-indeed,linkedin,zip_recruiter,glassdoor}
      - DEFAULT_RESULTS_WANTED=${DEFAULT_RESULTS_WANTED:-20}
      - DEFAULT_DISTANCE=${DEFAULT_DISTANCE:-50}
      - DEFAULT_DESCRIPTION_FORMAT=${DEFAULT_DESCRIPTION_FORMAT:-markdown}
      - DEFAULT_COUNTRY_INDEED=${DEFAULT_COUNTRY_INDEED:-USA}
      - ENABLE_CACHE=${ENABLE_CACHE:-false}
      - CACHE_EXPIRY=${CACHE_EXPIRY:-3600}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - ENABLE_HEALTH_ENDPOINTS=${ENABLE_HEALTH_ENDPOINTS:-true}
      - ENABLE_DETAILED_HEALTH=${ENABLE_DETAILED_HEALTH:-true}
      - ENABLE_SWAGGER_UI=${ENABLE_SWAGGER_UI:-true}
      - ENABLE_REDOC=${ENABLE_REDOC:-true}
    restart: unless-stopped

  worker:
    build: 
      context: https://github.com/gilby125/jobspy-api.git#main
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-jobspy}:${POSTGRES_PASSWORD:-jobspy_password}@postgres:5432/${POSTGRES_DB:-jobspy}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    restart: unless-stopped
    command: /bin/bash -c "cd /app && python -m celery -A app.celery_app worker --loglevel=info --concurrency=2"

volumes:
  postgres_data:
  redis_data:
EOF < /dev/null
