services:
  registry:
    image: registry:2
    container_name: local-docker-registry
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
    volumes:
      - registry_data:/data
    restart: unless-stopped

volumes:
  registry_data: