"""create_tracking_schema

Revision ID: b77c46b5c926
Revises: 0a6e5a8ae32e
Create Date: 2025-06-26 14:16:37.870731+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b77c46b5c926'
down_revision: Union[str, None] = '0a6e5a8ae32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('headquarters_location', sa.String(length=255), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('revenue_range', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('linkedin_company_id', sa.Integer(), nullable=True),
    sa.Column('glassdoor_company_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'domain', name='uq_temp_company_name_domain')
    )
    op.create_index(op.f('ix_temp_companies_id'), 'temp_companies', ['id'], unique=False)
    op.create_index(op.f('ix_temp_companies_name'), 'temp_companies', ['name'], unique=False)
    op.create_index(op.f('ix_temp_companies_domain'), 'temp_companies', ['domain'], unique=False)
    op.create_index(op.f('ix_temp_companies_industry'), 'temp_companies', ['industry'], unique=False)
    op.create_index(op.f('ix_temp_companies_linkedin_company_id'), 'temp_companies', ['linkedin_company_id'], unique=False)
    op.create_index('idx_temp_company_name_industry', 'temp_companies', ['name', 'industry'], unique=False)

    op.create_table('temp_job_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['temp_job_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_temp_job_categories_id'), 'temp_job_categories', ['id'], unique=False)
    op.create_index(op.f('ix_temp_job_categories_name'), 'temp_job_categories', ['name'], unique=True)

    op.create_table('temp_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'state', 'country', name='uq_temp_location')
    )
    op.create_index(op.f('ix_temp_locations_id'), 'temp_locations', ['id'], unique=False)
    op.create_index(op.f('ix_temp_locations_city'), 'temp_locations', ['city'], unique=False)
    op.create_index(op.f('ix_temp_locations_state'), 'temp_locations', ['state'], unique=False)
    op.create_index(op.f('ix_temp_locations_country'), 'temp_locations', ['country'], unique=False)
    op.create_index('idx_temp_location_country_state', 'temp_locations', ['country', 'state'], unique=False)

    op.create_table('temp_job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('job_category_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_interval', sa.String(length=20), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['temp_companies.id'], ),
    sa.ForeignKeyConstraint(['job_category_id'], ['temp_job_categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['temp_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('salary_min <= salary_max', name='chk_temp_salary_range'),
    sa.CheckConstraint('first_seen_at <= last_seen_at', name='chk_temp_date_range')
    )
    op.create_index(op.f('ix_temp_job_postings_id'), 'temp_job_postings', ['id'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_job_hash'), 'temp_job_postings', ['job_hash'], unique=True)
    op.create_index(op.f('ix_temp_job_postings_title'), 'temp_job_postings', ['title'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_company_id'), 'temp_job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_location_id'), 'temp_job_postings', ['location_id'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_job_category_id'), 'temp_job_postings', ['job_category_id'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_job_type'), 'temp_job_postings', ['job_type'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_experience_level'), 'temp_job_postings', ['experience_level'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_is_remote'), 'temp_job_postings', ['is_remote'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_salary_min'), 'temp_job_postings', ['salary_min'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_salary_max'), 'temp_job_postings', ['salary_max'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_first_seen_at'), 'temp_job_postings', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_last_seen_at'), 'temp_job_postings', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_temp_job_postings_status'), 'temp_job_postings', ['status'], unique=False)
    op.create_index('idx_temp_job_posting_company_status', 'temp_job_postings', ['company_id', 'status'], unique=False)
    op.create_index('idx_temp_job_posting_location_type', 'temp_job_postings', ['location_id', 'job_type'], unique=False)
    op.create_index('idx_temp_job_posting_salary_range', 'temp_job_postings', ['salary_min', 'salary_max'], unique=False)
    op.create_index('idx_temp_job_posting_dates', 'temp_job_postings', ['first_seen_at', 'last_seen_at'], unique=False)

    op.create_table('temp_job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('source_site', sa.String(length=50), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('easy_apply', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['temp_job_postings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_site', 'external_job_id', name='uq_temp_source_external_id'),
    sa.UniqueConstraint('job_posting_id', 'source_site', name='uq_temp_job_source_site')
    )
    op.create_index(op.f('ix_temp_job_sources_id'), 'temp_job_sources', ['id'], unique=False)
    op.create_index(op.f('ix_temp_job_sources_job_posting_id'), 'temp_job_sources', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_temp_job_sources_source_site'), 'temp_job_sources', ['source_site'], unique=False)
    op.create_index(op.f('ix_temp_job_sources_external_job_id'), 'temp_job_sources', ['external_job_id'], unique=False)
    op.create_index(op.f('ix_temp_job_sources_post_date'), 'temp_job_sources', ['post_date'], unique=False)
    op.create_index('idx_temp_job_source_site_date', 'temp_job_sources', ['source_site', 'post_date'], unique=False)

    op.create_table('temp_job_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('total_seen_count', sa.Integer(), nullable=False),
    sa.Column('sites_posted_count', sa.Integer(), nullable=False),
    sa.Column('days_active', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['temp_job_postings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_posting_id')
    )
    op.create_index(op.f('ix_temp_job_metrics_id'), 'temp_job_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_temp_job_metrics_last_activity_date'), 'temp_job_metrics', ['last_activity_date'], unique=False)

    op.create_table('temp_company_hiring_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('new_jobs_count', sa.Integer(), nullable=True),
    sa.Column('active_jobs_count', sa.Integer(), nullable=True),
    sa.Column('filled_jobs_count', sa.Integer(), nullable=True),
    sa.Column('avg_salary_min', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('avg_salary_max', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('top_job_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['temp_companies.id'], ),
    sa.ForeignKeyConstraint(['top_job_category_id'], ['temp_job_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_temp_company_date')
    )
    op.create_index(op.f('ix_temp_company_hiring_trends_id'), 'temp_company_hiring_trends', ['id'], unique=False)
    op.create_index(op.f('ix_temp_company_hiring_trends_company_id'), 'temp_company_hiring_trends', ['company_id'], unique=False)
    op.create_index(op.f('ix_temp_company_hiring_trends_date'), 'temp_company_hiring_trends', ['date'], unique=False)
    op.create_index('idx_temp_hiring_trend_date', 'temp_company_hiring_trends', ['date'], unique=False)
    op.create_index('idx_temp_hiring_trend_company_date', 'temp_company_hiring_trends', ['company_id', 'date'], unique=False)

    op.create_table('temp_scraping_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_site', sa.String(length=50), nullable=False),
    sa.Column('search_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_new', sa.Integer(), nullable=True),
    sa.Column('jobs_updated', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_scraping_runs_id'), 'temp_scraping_runs', ['id'], unique=False)
    op.create_index(op.f('ix_temp_scraping_runs_source_site'), 'temp_scraping_runs', ['source_site'], unique=False)
    op.create_index(op.f('ix_temp_scraping_runs_status'), 'temp_scraping_runs', ['status'], unique=False)
    op.create_index(op.f('ix_temp_scraping_runs_started_at'), 'temp_scraping_runs', ['started_at'], unique=False)
    op.create_index('idx_temp_scraping_run_site_status', 'temp_scraping_runs', ['source_site', 'status'], unique=False)
    op.create_index('idx_temp_scraping_run_started', 'temp_scraping_runs', ['started_at'], unique=False)

    op.create_table('temp_webhook_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('events', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_webhook_subscriptions_id'), 'temp_webhook_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_temp_webhook_subscriptions_is_active'), 'temp_webhook_subscriptions', ['is_active'], unique=False)
    op.create_index('idx_temp_webhook_active_events', 'temp_webhook_subscriptions', ['is_active', 'events'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_webhook_subscriptions')
    op.drop_table('temp_scraping_runs')
    op.drop_table('temp_company_hiring_trends')
    op.drop_table('temp_job_metrics')
    op.drop_table('temp_job_sources')
    op.drop_table('temp_job_postings')
    op.drop_table('temp_locations')
    op.drop_table('temp_job_categories')
    op.drop_table('temp_companies')
    # ### end Alembic commands ###
